nome = str(input('digite seu nome completo: ')).strip()
print('analisando seu nome...')
print('seu nome em maiusculo é {}'.format(nome.upper()))
print('seu nome em minusculo é {}'.format(nome.lower()))
print('seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print('seu primeiro nome é {} e possui {} letras'.format(separa[0], len(separa[0])))